#ifndef _HONEYWELL_SAMPLING_DATA
#define _HONEYWELL_SAMPLING_DATA

#define HONEYWELL_SAMPLING_DATA_PERIOD 10

typedef enum 
{
	HONEYWELL_START,
	HONEYWELL_NONE,
	HONEYWELL_WAIT_5ms,
	HONEYWELL_READ_DATA,
	HONEYWELL_SAMPLE_DATA_FINISH
}HONEYWELL_STATE;

void honeywell_sampling_data(void);


#endif //_HONEYWELL_SAMPLING_DATA


