#ifndef _MPXV70_SAMPLING_DATA_H
#define _MPXV70_SAMPLING_DATA_H


#define MPXV70_SAMPLING_DATA_PERIOD 10

#define MPXV70_SAMPLE_CNT 4

typedef enum
{
	MPXV70_NONE,
	MPXV70_SAMPLE_DATA,
	MPXV70_SAMPLE_FINISH
}MPXV70_STATE;

void MPXV70_sampling_data(void);

#endif //_MPXV70_SAMPLING_DATA_H

